apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-agent.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-agent.labels" . | nindent 4 }}
data:
  agent-config.yaml: |
{{ .Values.config.agentConfig | indent 4 }}
