apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-agent.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "ai-agent.selectorLabels" . | nindent 4 }}
